version: '3.12.4'

services:
    db:
        image: postgres:18.0
        restart: always
        container_name: postgresql
        volumes:
            -./data/db/var/lib/postgresql/data
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_DB=salasApi 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
        ports:
        - "5432:5432"
    